name: "Compilación del documento .tex de la carpeta Informes"

on: 
  push:
  branches:
  - main # Detecta cambios en el repositorio principal para ejecutar el código

jobs:
  release_cv:
  name: "Ejecucion Informe LaTex"
  runs-on: ubuntu-latest # Carga de la máquina virtual Linux

  steps:
  name: "Checkout master"
  uses: actions/checkout@v1 # Revisión de archivos en el repositorio

  name: "Compilación del informe"
  uses: xu-cheng/latex-action@master
  with:
    root_file: Informes/Informe01.tex # Compilación .tex

  name: "Revisión del PDF"
  run: |
    file Informe01.pdf | grep -q 'PDF'

  name: "Carga del PDF a una URL fija"
  uses: "marvinpinto/action-automatic-releases@latest"
  with:
    repo_token: "{{ secreats.PERSONAL_ACCESS_TOKEN}}"
    automatic_release_tag: "latest"
    prerelease: true
    title: "Carga"
    files: |
      Informe01.pdf


